name: flutter_tcp_example
description: Demonstrates how to use the TCP sockets in Flutter.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_local_notifications: ^5.0.0
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true