name: flutter_tcp_example
description: Demonstrates how to use the TCP sockets in Flutter.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_local_notifications: ^1.4.0
  bubble: ^1.1.9+1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true